# Generated by Django 4.2.7 on 2025-12-20 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=500)),
                ('categorie', models.CharField(default='analyses', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assurances',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('souscripteur', models.CharField(blank=True, max_length=255, null=True)),
                ('taux_couverture', models.CharField(blank=True, max_length=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='IPM',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ipms',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_prise_en_charge', models.CharField(blank=True, choices=[('IPM', 'IPM'), ('ASSURANCE', 'ASSURANCE')], max_length=10, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyse', models.ForeignKey(db_column='analyse_id', on_delete=django.db.models.deletion.CASCADE, to='api.analyse')),
                ('assurance', models.ForeignKey(blank=True, db_column='assurance_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assurance')),
                ('ipm', models.ForeignKey(blank=True, db_column='ipm_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ipm')),
            ],
            options={
                'db_table': 'tarifs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=100)),
                ('type_prise_en_charge', models.CharField(choices=[('IPM', 'IPM'), ('ASSURANCE', 'ASSURANCE')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assurance', models.ForeignKey(blank=True, db_column='assurance_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assurance')),
                ('ipm', models.ForeignKey(blank=True, db_column='ipm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ipm')),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevisLigne',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('analyse', models.ForeignKey(db_column='analyse_id', on_delete=django.db.models.deletion.PROTECT, to='api.analyse')),
                ('devis', models.ForeignKey(db_column='devis_id', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.devis')),
            ],
            options={
                'db_table': 'devis_lignes',
            },
        ),
        migrations.AddField(
            model_name='devis',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
